title: Sahib Virdee
url: "https://sahibvirdee.com"
description: Mechanical Engineering Student Portfolio

collections:
  content:
    output: true
    permalink: /:path/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag