site_name: Sahib Virdee
site_url: https://sahibvirdee.com

theme:
  name: material
  # custom_dir: overrides   <-- THIS WAS THE ERROR. DELETE THIS LINE.
  features:
    - navigation.instant
    - navigation.tabs
    - header.autohide
  font:
    text: Jost
    code: Roboto Mono
  palette:
    scheme: slate

markdown_extensions:
  - toc:
      permalink: false
plugins: []

extra_css:
  - stylesheets/extra.css

nav:
  - Personal: personal/index.md
  - Professional: index.md
  - Projects: projects/index.md
