site_name: Sahib Virdee
site_url: https://sahibvirdee.com

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant   # This makes it SUPER fast (SPA mode)
    - navigation.tabs      # Top level tabs
    - header.autohide      # Cleaner scrolling
  font:
    text: Jost             # Your requested font
    code: Roboto Mono
  palette:
    scheme: slate          # Dark mode base (we will override to True Black)

# Hide the sidebars to keep it minimalist
markdown_extensions:
  - toc:
      permalink: false
plugins: [] # Disables search

extra_css:
  - stylesheets/extra.css

nav:
  - Personal: personal/index.md
  - Professional: index.md
  - Projects: projects/index.md
